### PR TITLE
Allow specific version of chrome, provide examples with variants, and setup default executor [semver:minor]

### PR DESCRIPTION
**Pull request by dsayling**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Updates to have this orb pair with the browser variant. 

### Description

Add the ability to install a specific version of chrome. 
Update executor to define base-browser variant.
Update examples with executor, other browser variants and versions.

### CODE REVIEW

**Comment by gmemstr** [comment]
There has been some debate as to whether or not we want to cache binary downloads ourselves, and generally it hasn't been worth it because it places more burden on our caching system.

> Also adds support for specifying chrome versions on centos and debian based systems.

I think this is a good addition, but I'm unsure about caching the browser binaries. It might be more advantageous to encourage people to use the browser variants of `cimg` images when they become available.

**Comment by felicianotech** [comment]
> It might be more advantageous to encourage people to use the browser variants of cimg images when they become available.

This work is being done to enable the next-gen browser variants. We're trying to reduce some of the problems we had with them in the legacy images.

@glenjamin Do you have thoughts here?

If either of you are not aware of the browser variant issues, let me know. We can Zoom or I can write it here. I'll see if I already wrote it down somewhere.

**Comment by glenjamin** [comment]
I like the idea of having a tarball on S3 we can share between all of our docker images.

I'm not sure how well that would work in practice though

**Comment by felicianotech** [comment]
@dsayling Is this good to go minus removing caching? Shall I get started on that?

Also, the default executor is a Python image?

**Comment by dsayling** [comment]
No, the default executor should definitely change.

I set it as the default for my own ease. I forgot to ask what image you think should be the default? I assume ther would be a base variant, but didn't know what that would look like.

I can remove the caching logic if you haven't already, otherwise the only thing that really needs to be added is the ability to specify the chrome version. That was the only set of functionality I really added outside of the cachcing. If we want it to move it to use the new dev-kit way and move stuff to scripts - that will take a little longer.

**Comment by dsayling** [comment]
This orb needs a large rewrite to support the scripts packing in the orb dev kit, but I hope we can get this functionality out in the wild. Maybe when we GA the browsers, we can do a major update on the orb?

**Review by felicianotech — COMMENTED** [review]
LGTM

**Pull request merged**
